import { Button, Container, Stack } from '@mui/material';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <meta
               name='viewport'
               content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main>
            <Container sx={{ textAlign: 'center' }}>
               <h1>Landing Page</h1>

               <Stack direction='row' gap={3} justifyContent='center'>
                  <Button variant='contained' component={Link} href='/app'>
                     Go to Web App
                  </Button>

                  <Button variant='outlined' disabled href='/#'>
                     Get the Android App
                  </Button>
               </Stack>
            </Container>
         </main>
      </>
   );
}
